"""empty message

Revision ID: 038b9cfc2bfa
Revises: 1a3bf1243567
Create Date: 2022-11-24 19:47:05.562559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038b9cfc2bfa'
down_revision = '1a3bf1243567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people_favorite')
    # ### end Alembic commands ###
