"""empty message

Revision ID: 1c7b2229d954
Revises: 952d64f57643
Create Date: 2022-11-24 19:58:40.281141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7b2229d954'
down_revision = '952d64f57643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_char',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('peoplefavorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peoplefavorite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], name='peoplefavorite_people_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='peoplefavorite_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='peoplefavorite_pkey')
    )
    op.drop_table('favorite_char')
    # ### end Alembic commands ###
