"""empty message

Revision ID: 952d64f57643
Revises: 038b9cfc2bfa
Create Date: 2022-11-24 19:53:33.584621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952d64f57643'
down_revision = '038b9cfc2bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peoplefavorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('people_favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_favorite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], name='people_favorite_people_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='people_favorite_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='people_favorite_pkey')
    )
    op.drop_table('peoplefavorite')
    # ### end Alembic commands ###
